name: bingtray
version: 0.0.6
summary: cross-platform bing daily image wallpaper downloader.
description: |
  Select Wallpaper from Bing Images of the Day.
  Open source, cross-platform, written in Rust.

base: core20
confinement: strict

apps:
  bingtray:
    command: bin/bingtray
    plugs:
    - home

parts:
  bingtray:
    source-type: git
    source: https://github.com/nikescar/bingtray.git
    source-tag: 0.0.6
    plugin: rust
    rust-revision: nightly-2020-01-15
    build-packages:
      - libssl-dev
      - pkg-config
      - gettext
      - libclang-8-dev
      - on arm64,armhf,ppc64el,s390x:
        - lld-8
    override-build: |
      snapcraftctl set-version $(git describe --tags)
      export PATH=$PATH:$HOME/.cargo/bin
      rustup install stable
      cargo +stable install --force wasm-pack

      # Only Tier 1 Rust platforms get rust-lld
      # On the others (arm64, armhf, powerpc64, s390x) fall back to using
      # the system LLD we've installed earlier.
      case ${SNAPCRAFT_ARCH_TRIPLET} in \
        aarch64-linux-gnu|arm-linux-gnueabihf|powerpc64-linux-gnu|s390x-linux-gnu) \
          RUSTFLAGS="-C linker=lld" wasm-pack build --target web --release plume-front \
          ;; \
        *) \
          wasm-pack build --target web --release plume-front \
          ;; \
      esac

      cargo install --force --no-default-features --features sqlite --path . --root ${SNAPCRAFT_PART_INSTALL}
      cargo install --force --no-default-features --features sqlite --path plume-cli --root ${SNAPCRAFT_PART_INSTALL}
      cp -a assets migrations static target translations ${SNAPCRAFT_PART_INSTALL}
      cp snap/local/set-environment ${SNAPCRAFT_PART_INSTALL}
    stage-packages:
      - openssl