[package]
name = "bingtray-core"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
directories = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
attohttpc = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
scraper = { workspace = true }
wallpaper = { workspace = true }
