name: bingtray
version: 0.0.6
summary: cross-platform bing daily image wallpaper downloader.
description: |
  Select Wallpaper from Bing Images of the Day.
  Open source, cross-platform, written in Rust.

base: core20
confinement: strict

architectures:
  - build-on: amd64

apps:
  bingtray:
    command: bin/bingtray
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy

parts:
  bingtray:
    source: .
    plugin: rust
    build-packages:
      - libssl-dev
      - pkg-config
      - gettext
      - libclang-dev
      - musl-tools
    override-build: |
      # Install Rust with musl target for static linking
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
      export PATH="$HOME/.cargo/bin:$PATH"
      source $HOME/.cargo/env
      
      rustup target add x86_64-unknown-linux-musl
      
      snapcraftctl set-version $(git describe --tags --always 2>/dev/null || echo "0.0.6")
      
      # Build with musl for static linking
      cargo build --package bingtray --release --target x86_64-unknown-linux-musl
      install -Dm755 target/x86_64-unknown-linux-musl/release/bingtray $SNAPCRAFT_PART_INSTALL/bin/bingtray